NumPy Project – Step by Step Explanation
Step 1: Introduction
NumPy (Numerical Python) is a Python library used for numerical and scientific computing.
It provides support for working with arrays and performing mathematical and statistical operations efficiently.

step2:creating arrays

 Objective of the Project
The objectives of this project are:
To understand NumPy basics
To create one-dimensional and two-dimensional arrays
To perform array operations
To apply statistical functions using NumPy

step 3:tools used(https:// [link text](https://))

 Tools Used
Python
NumPy
Google Colab / Jupyter Notebook
GitHub (for collaboration and repository management)

step 4:impoting NumPy

 Importing NumPy
NumPy library is imported using the alias np.



 import numpy as np




Step 5: Creating NumPy Arrays
One-dimensional and two-dimensional arrays are created using NumPy.

In [4]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
print("1D array:",arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr2)





1D array: [10 20 30 40 50]
2D array:
 [[1 2 3]
 [4 5 6]]


step 6:Array properties and indexing and accessing elements


Array properties are used to understand the structure of the array.
Shape – gives dimensions
Size – total number of elements
Data type – type of elements

In [5]:
print("first element of 1D array:",arr1[0])
print("elements from index 1 to 3:",arr1[1:4])
print("element at row 1,col 2:",arr2[0,1])



first element of 1D array: 10
elements from index 1 to 3: [20 30 40]
element at row 1,col 2: 2


step 7:Mathematical and statical operations

- np.sum() → sum of array elements
- np.mean() → mean of array elements
- np.max() → maximum element
- np.min() → minimum element
- axis parameter:
    - axis=0 → sum along columns
    - axis=1 → sum along rows

In [6]:
print("sum of 1D array:",np.sum(arr1))
print("mean of 1D array:",np.mean(arr1))
print("maximum value in 1D array:",np.max(arr1))
print("minimum value in 1D array:",np.min(arr1))




sum of 1D array: 150
mean of 1D array: 30.0
maximum value in 1D array: 50
minimum value in 1D array: 10


In [7]:

print("sum along rows OF 2D array:",np.sum(arr2,axis=1))
print("sum along columns of 2D array:",np.sum(arr2,axis=0))



sum along rows OF 2D array: [ 6 15]
sum along columns of 2D array: [5 7 9]


Step 8: reshaping arrays

*   List item
*   List item



- Reshaping changes the shape of an array without changing its data.
- Use arr.reshape(rows, columns) for 2D arrays.

In [8]:
arr3=np.array([1,2,3,4,5,6])
print(arr3.reshape(2,3))


[[1 2 3]
 [4 5 6]]


Step 9: Broadcasting:

- Broadcasting allows arithmetic operations between arrays of different shapes.
- Smaller array is broadcasted to match the shape of the larger array.

In [9]:
arr4 = np.array([1,2,3])
broadcasted = arr4 + 5
print("broadcasted array:", broadcasted)

broadcasted array: [6 7 8]


Step 10: Saving and Loading Arrays


- NumPy arrays can be saved to a file using np.save().
- np.load() is used to load saved arrays.

In [11]:
np.save("sample.npy", arr1)
loaded = np.load("sample.npy")
print(loaded)

[10 20 30 40 50]


Step 11: Element-wise Operations

- NumPy supports element-wise operations like addition, multiplication, and exponentiation.
- Operations are faster than Python lists.

In [12]:

print(arr1 ** 2)


print(arr1 + arr1)

[ 100  400  900 1600 2500]
[ 20  40  60  80 100]


Step 12: Performance Comparison with Python Lists


- NumPy operations are faster than Python lists for large data.
- Demonstrates time difference for incrementing elements.

In [13]:
import time

# Python list
py_list = list(range(1000))
start = time.time()
py_list = [x+1 for x in py_list]
print("Python list time:", round(time.time()-start,6))

# NumPy array
np_array = np.array(range(100000))
start = time.time()
np_array = np_array + 1
print("NumPy array time:", round(time.time()-start,6))

Python list time: 0.000154
NumPy array time: 0.001184


Step 13: Conclusion

This project provides a clear understanding of NumPy fundamentals.
It demonstrates how NumPy simplifies data handling and numerical computations.
The project also introduces version control and collaboration using GitHub.